### PR TITLE
Add support for sending additional HTTP headers

### PR DESCRIPTION
**Pull request by mhariri**

### CODE REVIEW

**Comment by mhariri** [comment]
I will send a PR for smack project as well to be able to use this header adding feature.

**Comment by Flowdalic** [comment]
> I will send a PR for smack project as well to be able to use this header adding feature.

That should probably be a PR against Smack's 4.3 branch and will require an adjustment to version specification of the jbosh dependency declaration in smack-bosh/build.gradle

**Comment by mhariri** [comment]
True. Do you agree with that change? Should I create a PR?

Just for some background, I've modified smack lib to support Cisco ECE, which talks a slightly modified version of XMPP. Now I'm sending back the changes that I made there in order to improve the base projects, and hopefully depend on these ones instead of copying the code in there.

https://github.com/mhariri/smack-ece

**Comment by Flowdalic** [comment]
> Just for some background, I've modified smack lib to support Cisco ECE, which talks a slightly modified version of XMPP. Now I'm sending back the changes that I made there in order to improve the base projects, and hopefully depend on these ones instead of copying the code in there.

That is great and highly appreciated. Thank you. Feel free and invited to join the Smack developer community in the [forums](https://discourse.igniterealtime.org/), XMPP (smack@conference.igniterealtime.org) or IRC (#smack, freenode), so we can coordinate our efforts.

**Pull request merged**
